version: "3"

services:
  postgres:
    container_name: saloodo_postgres
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/data/db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: saloodo

  server:
    container_name: saloodo_server
    build: server
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./server:/app/server
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: saloodo
      DB_PORT: 5432
      JWT_SECRET: secret

  client:
    container_name: saloodo_client
    build: client
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app/client
    environment:
      VITE_BASE_URL: "http://localhost:4000"

volumes:
  db:
    driver: local
